### ISSUE TITLE
How can I re-create indexes and auth with node-mongo-seeds?

### ISSUE THREAD

**Issue by joaocc** [toymachiner62/node-mongo-seeds#17]
I want to recreate a seed MongoDB database, but I also need to add indexes and auth.
Any ideas?
Thx

**Comment by toymachiner62** [comment]
node-mongo-seeds currently doesn't support creating indexes. Pull requests are welcome if you want to implement that. 

As far as auth are you referring to create users for mongodb? If so, that is also not implemented at this time. Again pull requests are welcome for this too.
