### ISSUE TITLE
Enhancement: Compatibility with remote mongodbs

### ISSUE THREAD

**Issue by tmartyny** [toymachiner62/node-mongo-seeds#18]
@toymachiner62 
Thanks for talking with me about this today.

Feature: Ability to seed a remote database
Example: { "dev": "mongodb://sallyuser:sallypassword@aabb22.mongolab.com:11111/nightscout" }

It would be ideal if it was implemented in a way that allows the user to not have their credentials in more than one place and instead allow:
{ "dev": credentials.mongo.development.connectionString }

**Comment by toymachiner62** [comment]
After looking into this a little bit, with your example, do you get an error? I would actually expect that to work. I have not created a mongo instance hosted on another server.

**Comment by tmartyny** [comment]
When I looked at the code you directed me to, I actually thought it should work as well, but didn't have time to dig into it. I did get an error. 

[Error: failed to connect to [undefined:27017]]

**Comment by toymachiner62** [comment]
I just created an account on mongo labs and tried this out and it seemed to work just fine. 

Can you either try again and send me some details or create a reproducible test case for me to try?

**Comment by toymachiner62** [comment]
Closed due to inactivity. Reopen if still an issue.
