### ISSUE TITLE
Mystery 'Unexpected token {' issue

### ISSUE THREAD

**Issue by jmsherry** [toymachiner62/node-mongo-seeds#19]
I'm trying to get the update a collection: I've mongoexport'd the data to a file like so:

    {"__v":0,"_id":{"$oid":"5549475f0b1fb36c1e205664"},"description":"Box of eggs","imageURL":"http://www.beingabusinesscelebrity.com/wp-content/uploads/2013/06/Sometimes-it-looks-like-an-eggbox.jpg","name":"Eggs","price":1,"quantity":"6"}
    {"__v":0,"_id":{"$oid":"55494a6d0b1fb36c1e205665"},"description":"Beef Burgers","imageURL":"http://www.roamingroosters.co.uk/images/uploads/grass_fed_beef/roaming-roosters-beef-burgers.jpg","name":"Burgers","price":1.95,"quantity":"2"}
    etc....

seeds.json looks like:
    `{
        "undefined": "localhost/kitchenapp",
        "dev": "localhost/kitchenapp-dev",
        "prod": "localhost/kitchenapp"
    }`

I run `seed` from the command line and get:

    Jamess-MacBook-Pro:ka2 jamessherry$ seed
    [Error: Module version mismatch. Expected 46, got 14.]
    js-bson: Failed to load c++ bson extension, using pure JS version
    Seeding files from directory /Users/jamessherry/sites/ka2/seeds
    ----------------------
    Seeding collection ingredients
    [SyntaxError: /Users/jamessherry/sites/ka2/seeds/ingredients.json: Unexpected token {]

Has anyone encountered this?

Seed.json is generated to begin as a config object, and even if you turn ingredients.json into a JSON collection (as opposed to what mongoexport outputs) it still throws the same error...

**Comment by toymachiner62** [comment]
Can you post your ingredients.json file?

**Comment by toymachiner62** [comment]
Or can you start with a very simple file and see if that seeds. Then keep adding more data until you narrow it down to some specific data?

**Comment by jmsherry** [comment]
Hi @toymachiner62 , The first snippet of code is the first few lines of the ingredients.json

If I take it down to one object in that file, I get:

    [Error: Seed file recipes does not start with an Array]
    [Error: key $oid must not start with '$']

Does this means that I can't `mongoexport` into a file and then use that file with this package? Would I have to reformat it's output somehow?

**Comment by toymachiner62** [comment]
Yes so you have 2 issues:

1. Your json file needs to be an array so with your example content, if you just put them in an array like this:
```json
[
  {"__v":0,"_id":{"$oid":"5549475f0b1fb36c1e205664"},"description":"Box of eggs","imageURL":"http://www.beingabusinesscelebrity.com/wp-content/uploads/2013/06/Sometimes-it-looks-like-an-eggbox.jpg","name":"Eggs","price":1,"quantity":"6"}
  {"__v":0,"_id":{"$oid":"55494a6d0b1fb36c1e205665"},"description":"Beef Burgers","imageURL":"http://www.roamingroosters.co.uk/images/uploads/grass_fed_beef/roaming-roosters-beef-burgers.jpg","name":"Burgers","price":1.95,"quantity":"2"}
]
```
It will solve your first error.

2. I'm guessing that you cannot insert into mongo json that contains a `$` because mongo uses them for it's functions. I'm not 100% sure on that, but that's my gut feeling. You can verify by trying to manually insert something into mongo that contains a `$`.
