### ISSUE TITLE
Exclude Json File ?

### ISSUE THREAD

**Issue by aldrienht** [toymachiner62/node-mongo-seeds#20]
Is there an option in "seed" command that can exclude some json file when migrating data. Aside from manually relocating the file outside /seeds directory ?

Thank you very much.

**Comment by toymachiner62** [comment]
No there is not. Why would you store a file in that folder if you don't want to seed it to mongo? You could name the file with a different extension than .json so that it isn't seeded to mongo.

**Comment by aldrienht** [comment]
Hi @toymachiner62 . Thank you for clarification.
I'm just thinking about it since I currently used the seed for generating default table/fields and data.
For example you made the first seed/migration, eventually you will have some real data on DB due to updates.
Then example, you  want update for some .json file to add some fields or change field name.
When you seed it again it will overwrite the real data on DB as said in documentation.

So, maybe the best solution is like what you have said, is to change the extension name and rename it again once finished seeding.

Thank you.

**Comment by toymachiner62** [comment]
Got it. I would suggest using something similar to rails migrations.
There's a similar package I've used before and I think it was called
node-db-migrate or something.

On Monday, January 18, 2016, aldrienht <notifications@github.com> wrote:

> Hi @toymachiner62 <https://github.com/toymachiner62> . Thank you for
> clarification.
> I'm just thinking about it since I currently used the seed for generating
> default table/fields and data.
> For example you made the first seed/migration, eventually you will have
> some real data on DB due to updates.
> Then example, you want update for some .json file to add some fields or
> change field name.
> When you seed it again it will overwrite the real data on DB as said in
> documentation.
>
> So, maybe the best solution is like what you have said, is to change the
> extension name and rename it again once finished seeding.
>
> Thank you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/toymachiner62/node-mongo-seeds/issues/20#issuecomment-172695737>
> .
>


-- 
Tom Caflisch
507.202.0087
TomCaflisch@gmail.com
http://allthingswebdesign.com
