### ISSUE TITLE
Extend with MongoDB Json syntax

### ISSUE THREAD

**Issue by pjanuario** [toymachiner62/node-mongo-seeds#22]
Currently we are unable to specify datatypes on seeds and this is very usefull.
I would suggest that we extend this with this library https://github.com/watson/json2mongo that already handles the Extend MongoDB json syntax.

Related with #21

**Comment by blueror815** [comment]
Hi Guys.
I have an error when I run this command on AWS
Please check out my screenshot here.
https://www.evernote.com/l/Arkf-o1FaRFFF6zXIqx3XEmqQ-faIhmq3kE
I hope you help me asap.
I am waiting for your quick reply.
Best regards

**Comment by blueror815** [comment]
Hi 
I have updated my node version with 5.9.0
And my npm version is 3.7.3
After upgrading, I can not run command   $ seed.
I have run $ npm install
And when I am going to run $ seed
But I have found such this error.
https://www.evernote.com/l/Arnvi_DnZlJAHZMosI1j4Z-JR7aRSwYTFbs

**Comment by toymachiner62** [comment]
@blueror815 First you should ask your own question next time instead of hijacking @pjanuario's question.

You need to install node-mongo-seeds globally. If this doesn't fix your issue please ask your own question on here and I can help you out.
