### ISSUE TITLE
populating the `_id` field

### ISSUE THREAD

**Issue by tjaartvdwalt** [toymachiner62/node-mongo-seeds#24]
Hi, thanks for a good tool.

This may be a noob question, but I am grappling with how I should deal with the `_id` field when populating seed data for a collection that has references to the `_id` field of other collections.

I like to let the `_id` field get auto generated by mongo, but it seems that manually setting this field is the only way that I will be able to control the dependencies.

Is this good practice, or is there a better solution?
Is there any negative side effects I should be aware of?

**Comment by toymachiner62** [comment]
Kind of a loaded question so I'll try to address it all.

If you look at the normalized data model on mongo's docs https://docs.mongodb.org/manual/core/data-model-design/ you can see that the normalized model is fully acceptable. node-mongo-seeds creates the `_id` automatically for every record that it seeds. 

Currently node-mongo-seeds does not have support to reference _id's that are generated from another file.

I would say that the way node-mongo-seeds generates it's own `_id` for every record, it is not good practice to set your own `_id` along with node-mongo-seeds b/c there is a difference between some field you are calling an `id` and an actual `OID` in mongo. However it is perfectly acceptable to generate your own `_id`'s in mongo as long as you ensure they are set as an actual `oid` and not just some string which you are calling an `id`.

Does that make sense?

**Comment by tjaartvdwalt** [comment]
@toymachiner62 thanks for the reply, it makes sense.

I ended up writing a script that sets the references after the data has been seeded.

**Comment by thevalyreangroup** [comment]
@tjaartvdwalt Could you please advise how you did this? I also need to seed an array of referenced OID's.
