### ISSUE TITLE
Promise Issue

### ISSUE THREAD

**Issue by danielmhair** [toymachiner62/node-mongo-seeds#26]
While trying to populate over 100,000 documents using your module (which is great by the way), I noticed that only 999 documents were inserted. After looking at your code, I noticed that you returned a resolve before inserting them. Added the else statement to solve it. This fixed my error. Here is pull request for this fix: https://github.com/toymachiner62/node-mongo-seeds/pull/25

**Comment by toymachiner62** [comment]
Fixed by #25
