### ISSUE TITLE
How do I connect to the new mongodb

### ISSUE THREAD

**Issue by robbydrop13** [toymachiner62/node-mongo-seeds#32]
Hi,

How can I connect to the seed mongo db? Should I update: 'mongoose.connect('mongodb://localhost/DBNAME');'
in server.js? 

Thanks!

Robin

**Comment by toymachiner62** [comment]
If you're using mongoose I suggest you have a look at the [mongoose documentation](http://mongoosejs.com/) on how to connect to your mongodb instance.
