### ISSUE TITLE
Seed hanging

### ISSUE THREAD

**Issue by kayaelle** [toymachiner62/node-mongo-seeds#34]
When running seed, it just hangs. Ran the tests and am getting a timeout error: Error: timeout of 5000ms exceeded

I'm running this on a local machine. Can you advise? Thanks

**Comment by toymachiner62** [comment]
How many files or whats the size of the json files? Relatively small?

**Comment by toymachiner62** [comment]
I just added a new version 2.3.1 of node-mongo-seeds to npm. Try updating and see if that helps.
