### ISSUE TITLE
Feature Request: Add seed.js so you can fill in values from another file

### ISSUE THREAD

**Issue by dancancro** [toymachiner62/node-mongo-seeds#35]
This is a great tool. Thanks!

I just spent a day or so on a problem that came from having two databases when I thought there was just one. One of them was seeded and the other one was tied to my app because there were two places to put the database name and at some point I had changed it in only one of them. Oops!

A solution to this would be to offer the option for a `seed.js` file in addition to the `seed.json` file. The `seed.js` file would export an object like `seed.json` contains but form it dynamically using javascript to read configuration values from somewhere else.

That way `node-mongo-seed` would look for `seed.json` then `seed.js`, or the other way around,  and use that to do the seeding.

**Comment by toymachiner62** [comment]
Can you elaborate on your use case with some example folder structure and simple code?

**Comment by JREAM** [comment]
```
/seeds
  /accounts.json
  /content.json  <-- Uses '_id' from accounts.json
  /contentMeta.json  <-- Uses '_id' from content.json
```

**Comment by toymachiner62** [comment]
So in this case would you manually specify the `_id` to be used in `accounts.json` and then also specify that same `_id` in `content.json`  as an attribute which points to a specific account record?

**Comment by toymachiner62** [comment]
Version 3.0.1 released. 66d6ac1d9a02ed1e02fd3cc63884e28f303f5f3b

**Comment by toymachiner62** [comment]
Also published to NPM

**Comment by toymachiner62** [comment]
Note the changelog for what has changed since this was a breaking change https://github.com/toymachiner62/node-mongo-seeds/blob/master/CHANGELOG.md
