### ISSUE TITLE
what about having different seed folder ?

### ISSUE THREAD

**Issue by BassemDev** [toymachiner62/node-mongo-seeds#37]
isn't a good feature to add possibility of seeding with different json collections.
Actually right now we just create a seeds folder and put on it the json mongodb document.
What about having different seeds folder, because as developer sometimes i want to initialise the database but sometime i want to seed the database with some specific h-case or conditions. isn't better to have like
initalSeeds folder and smallProductionseedFolder and of course a way for a developer to choose which one to seed the mongoDB with.

**Comment by toymachiner62** [comment]
Interesting idea. I originally created this module based on the way that Ruby on Rails does seeding. There isn't a way to specify separate seed data. Not so say that it's not a bad idea though. Let me do some thinking on this.

**Comment by BassemDev** [comment]
i would be happy to help in this if you want because it will be a good feature and a great one since we are talking about seeding data.

**Comment by BassemDev** [comment]
i was just checking the lib and i discover that's hard coded here 
`var dir     = process.cwd()+'/seeds';`

maybe we could change this to the same idea used in the seed.json where there is different environment !

**Comment by toymachiner62** [comment]
Please do submit a PR for this.

**Comment by mmelzalabany** [comment]
Good day pals. Any news about this feature? Is it added and functional now?

**Comment by toymachiner62** [comment]
I have not done any work on this. @mmelzalabany can you provide your use case on how you'd want to use this feature if implemented?

**Comment by mmelzalabany** [comment]
Sure. The thing that I am having a db shot in the seeds folder, that I am going to use every time I run my selenium tests.

My case is: I am going to have different test scenarios, for various tasks. For example, I want to test the list items page while it has no items, it has 1 item, and when it has 11 items to test pagination, for example. So I am going to need like 3 db seeds folder: seeds-no-items-scenario, seeds-one-item-scenario, and seeds-11-items-scenario.

I hope I clarified my use case in a good and clear manner. Waiting for your reply.

**Comment by toymachiner62** [comment]
Make sense. I'll get started on this feature.

**Comment by toymachiner62** [comment]
Added the `--seeds-folder` flag to the `seed` command https://github.com/toymachiner62/node-mongo-seeds#seed

This is available on version 3.1.0 which is now available on npm.

**Comment by mmelzalabany** [comment]
Can't thank you enough. Works like a charm!
