### ISSUE TITLE
Is there a way to seed mongoose associations with the json file?

### ISSUE THREAD

**Issue by dylanjha** [toymachiner62/node-mongo-seeds#38]
For example:

If you have a Post model and you have a Comment model. For example if the schemas looks like this, what would the JSON files looks like in order to properly insert ObjectIds to the associated model?

```javascript
const commentSchema = new Schema({
  body: String,
  post: {type: Schema.Types.ObjectId, ref: 'Post', required: true, index: true}
})
 mongoose.model('Comment', commentSchema)

const postSchema = new Schema({
  title: String
})
 mongoose.model('Post', postSchema)
```

Thank you! Maybe this is out of the scope of this tool, but figured I would ask, maybe there is a way I don't know about.

**Comment by BassemDev** [comment]
@dylanjha it will be a simple reference between the documents within the two json file:
i fwill give you an example of how it could look like: 
**comment.json**
`[{
 "_id" : {"$oid":"59316b89008c586bc2214318"},
 "body" : "some data",
"post" : {"$oid":"59316b89627c586bc2214666"}
}]`

**post.json**
`[{
 "_id" : {"$oid":"59316b89627c586bc2214666"},
"title" : "comment title"
}]`
