### ISSUE TITLE
Importing data with type

### ISSUE THREAD

**Issue by rcosta-gcare** [toymachiner62/node-mongo-seeds#40]
Here is my problem.
I have a json structure with the _id defined, here it what looks like:
`[{
  "_id": {"$oid" : "000000000000000000000002"},
  "accountName" : "Test",
  "status" : "ACTIVE"
}]`

But I get this error: Error: $oid is not valid for storage.

Just for test purposes, I added the following [json](https://github.com/toymachiner62/node-mongo-seeds/blob/master/test/validExtended/seeds/extended.json) to my seeds folder, and I notice that the date was added incorrectly.
Here is the preview.
![Image with the error](https://image.ibb.co/fWM3Sv/Screen_Shot_2017_07_18_at_2_28_03_PM.png)

Note that signup_date is an object with $date inside also the type is string.

I think this is an error, and both errors are related.

**Comment by toymachiner62** [comment]
Looks like this is a bug. I'll try to find time to work on it in the next couple weeks. PR's welcome.

**Comment by toymachiner62** [comment]
Hmm i just ran the tests and it looks like it correctly inserted signup_date as a Date object for me. Do you get the same results when you download this repo and run `npm test`?

![screenshot at jul 31 22-57-42](https://user-images.githubusercontent.com/485782/28808732-0138a9b0-7644-11e7-9751-e6de54df85d4.png)

**Comment by rcosta-gcare** [comment]
Hey @toymachiner62 Thanks for the support, I just figured out what was wrong, my seed file was an object instead of an array.
