### ISSUE TITLE
Seed document references

### ISSUE THREAD

**Issue by jvguillen** [toymachiner62/node-mongo-seeds#42]
How do you do seed a document that includes a reference to another seeded document? Should I just hardcode the ids?

EDIT: I realized that there is not simple way to hardcode the _id of a document as the module treats it as a string

**Comment by toymachiner62** [comment]
Unless this is provided by the extended json syntax, this is not possible at this time.

https://github.com/toymachiner62/node-mongo-seeds/issues/13

**Comment by toymachiner62** [comment]
I just added a test for this and it works. Here's an example of how it's done in the seed file.

https://github.com/toymachiner62/node-mongo-seeds/blob/master/test/validExtended/seeds/extended.json#L3-L5

**Comment by jvguillen** [comment]
hey @toymachiner62 thanks for the replay. I also implemented the mongo-extended-json successfully. However, I encountered a different case for date. I'd be grate to create timestamps on run time so fields like `updated_at` wouldn't have to be hardcoded. Anyways, sweet module. Thanks!
