### ISSUE TITLE
File name with more than one "." before the extension 

### ISSUE THREAD

**Issue by bmutinda** [toymachiner62/node-mongo-seeds#48]
Was scanning through the code and found out this line that assumes all filename should follow this 
`filename.ext` format while some filenames might have more than 1 "." e.g. `multiple.dots.ext`

For the said example, you will just assume the collection name will be `multiple`.

If you have mentioned the file naming conventions somewhere, feel free to highlight otherwise it might not give the desired results.

https://github.com/toymachiner62/node-mongo-seeds/blob/925fd618686c436be22ff6608abb299da9ac37b8/lib/seed.js#L93

**Comment by toymachiner62** [comment]
Using dot in the collection name is pretty non-standard when it comes to naming conventions in mongodb so i'm inclined to not address this.
