### ISSUE TITLE
Fix { [MongoError: Invalid Operation, No operations in bulk] name: 'MongoError' }

### ISSUE THREAD

**Issue by toymachiner62** [toymachiner62/node-mongo-seeds#6]
Depending on what you're inserting, you can the error: `{ [MongoError: Invalid Operation, No operations in bulk] name: 'MongoError' }`

Need to figure out what is causing this and how to fix it.

**Comment by GeoffreyPlitt** [comment]
+1 I'm getting this error and hoping to get to the bottom of it.

**Comment by toymachiner62** [comment]
Ok i still don't understand exactly what this new bulk api is all about. I read this http://blog.mongodb.org/post/84922794768/mongodbs-new-bulk-api but I still don't know what exactly it means is causing the issue with this package.

From this http://docs.mongodb.org/manual/reference/method/db.collection.insert/ I should be able to insert an array of documents into mongo.

I also don't know how to create a simple reproducible test case.

**Comment by GeoffreyPlitt** [comment]
I just found out this error may happen if an empty array is passed. I could swear I'm not sending empty arrays, but I'll do some tests to verify.

**Comment by toymachiner62** [comment]
Good find @GeoffreyPlitt! My project that I was seeing this error does have an empty array collection. This should be fixed now and pushed to the npm repo so if you update your node-mongo-seeds you shouldn't see this error anymore.

**Comment by vodich** [comment]
Anybody know if there is a way to check if there are operations in bulk before executing ? I am preety sure I don't send any empty objects but keep getting this error "Invalid Operation, No operations in bulk"

**Comment by toymachiner62** [comment]
@vodich this issue seems to be resolved via this commit https://github.com/toymachiner62/node-mongo-seeds/commit/b65f25ed35164226b036d41093720b0520a0813e. Are you using the latest version of node-mongo-seeds?

**Comment by panickz** [comment]
Doenst need to be an empty object. Im getting this error to. In my case I was trying to send an array instead of an object. I was declaring my global object like "var obj = []". Which produce something like [0:'foo',1:'bar']. Mongo is expecting data enclosured like {} or [{}] so I just changed the way I was declaring the variable to {}. Hope it helps.

**Comment by toymachiner62** [comment]
`[0:'foo',1:'bar']` is not valid json anyways so i wouldn't expect that to work. There could be better error handling for it in this library though i suppose.

**Comment by ningappa** [comment]
var mongoose     = require('mongoose');
var Schema       = mongoose.Schema;

// Define our results schema
var webSchema = new Schema({"abc" : String},{
    collection: 'web_v2'
});
MyApi.prototype.Webs= mongoose.model('Webs', webSchema);
resultData = [{"abc": "12121221"},{"abc": "44545"},{"abc": "545"}]
MyApi.prototype.Webs.collection.insert(resultData, function (err, myDocuments) {
                        if (err) {
                            console.log(err);
                        } else {
                            console.log("web inserted : " + myDocuments.result.n);
                        }
                    });

I'm getting the error 

MongoError: Invalid Operation, No operations in bulk
    at Function.MongoError.create (/pathtoapp/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11)
    at toError (/pathtoapp/node_modules/mongoose/node_modules/mongodb/lib/utils.js:114:22)
    at OrderedBulkOperation.execute (/pathtoapp/node_modules/mongoose/node_modules/mongodb/lib/bulk/ordered.js:500:11)
    at bulkWrite (/pathtoapp/node_modules/mongoose/node_modules/mongodb/lib/collection.js:582:8)
    at Collection.insertMany (/pathtoapp/node_modules/mongoose/node_modules/mongodb/lib/collection.js:477:44)
    at Collection.insert (/pathtoapp/node_modules/mongoose/node_modules/mongodb/lib/collection.js:753:15)
    at NativeCollection.(anonymous function) [as insert] (/pathtoapp/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:136:28)
    at /pathtoapp/index.js:481:57
    at /pathtoapp/node_modules/async/lib/async.js:721:13
    at /pathtoapp/node_modules/async/lib/async.js:52:16
    at async.forEachOf.async.eachOf (/pathtoapp/node_modules/async/lib/async.js:236:30)
    at _parallel (/pathtoapp/node_modules/async/lib/async.js:712:9)
    at Object.async.parallel (/pathtoapp/node_modules/async/lib/async.js:726:9)
    at /pathtoapp/index.js:479:43
    at /pathtoapp/node_modules/async/lib/async.js:721:13
    at /pathtoapp/node_modules/async/lib/async.js:52:16

anyone please let me know what am i doing wrong.?

**Comment by toymachiner62** [comment]
@ningappa From the code you posted it doesn't even look like you're using node-mongo-seeds.

**Comment by gwendall** [comment]
Just check if the bulk instance has operations before calling `execute` with this function:

```
const BulkHasOperations = (b) => b && b.s && b.s.currentBatch && b.s.currentBatch.operations && b.s.currentBatch.operations.length > 0;
...
const bulk = db.collection('something').initializeUnorderedBulkOp();
...
BulkHasOperations(bulk) && bulk.execute();
```

**Comment by rbaindourov** [comment]
+1 A migration script I wrote just started throwing this error for me and it used to work before. 
https://github.com/rbaindourov/multiDomainCMS/blob/master/migration.js

**Comment by toymachiner62** [comment]
@rbaindourov did you recently upgrade your version of Mongo? What version of node-mongo-seeds are you using? Can you post the error stack trace?
