### ISSUE TITLE
Is process.exit() necessary or am i doing something wrong?

### ISSUE THREAD

**Issue by toymachiner62** [toymachiner62/node-mongo-seeds#7]
Is this `process.exit()` a necessary statement? Seems to hang without it. 

https://github.com/toymachiner62/node-mongo-seeds/blob/master/lib/seed.js#L40

**Comment by fmvilas** [comment]
Maybe you need to close MongoDB connection. I have no idea what can it be, just trying to guess :)

Hope it helps :+1:

**Comment by toymachiner62** [comment]
Good call @fmvilas

**Comment by fmvilas** [comment]
Glad it helped :smile:
